# This is a basic workflow to help you get started with Actions

name: Github Neoload Test 1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
 #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Install Neoload Packages"
        run: pip3 install -U neoload
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
      - uses: actions/checkout@v3.3.0
      
      - name: "Login Neoload Web"
        env:
          NEOLOAD LOGIN: ${{ff3fe55ad3893b8456ef362e47cbbbf3466d6a6f9c0d4a91}}
        run: neoload login $ff3fe55ad3893b8456ef362e47cbbbf3466d6a6f9c0d4a91
      
      - name: Use workspace
        run: neoload workspaces use

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
